trigger:
- main

pool:
  name: DevOps PRJ
  demands:
    - Agent.Name -equals NINETY2

variables:
  JAVA_HOME: 'C:\\Program Files\\Java\\jdk-23'

steps:

- task: Maven@3
  inputs:
    mavenPomFile: 'pharmaliv/pom.xml'
    goals: 'clean package'
    mavenVersionOption: 'Default'
    options: '-Xmx1024m'
  env:
    JAVA_HOME: $(JAVA_HOME)

- task: CopyFiles@2
  inputs:
    contents: '**/target/*.war'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'pharmaliv-war'
    publishLocation: 'Container'
